# Configuration for graphrag-anthropic-llamaindex

# LLMプロバイダー選択: "anthropic" or "bedrock"
llm_provider: "bedrock"  # or "anthropic"

# Anthropic API直接使用時の設定
anthropic:
  # api_key は環境変数 ANTHROPIC_API_KEY から取得されます
  # export ANTHROPIC_API_KEY='your-api-key' を実行してください
  model: "claude-3-opus-20240620"
  # api_base_url: "https://api.anthropic.com"

# AWS Bedrock使用時の設定
bedrock:
  model: "anthropic.claude-3-sonnet-20240229-v1:0"
  region: "us-east-1"
  # aws_access_key_id: "YOUR_AWS_ACCESS_KEY"  # 環境変数AWS_ACCESS_KEY_IDを使用する場合は省略可
  # aws_secret_access_key: "YOUR_AWS_SECRET_KEY"  # 環境変数AWS_SECRET_ACCESS_KEYを使用する場合は省略可
  # aws_session_token: "YOUR_SESSION_TOKEN"  # セッショントークン（オプション）

embedding_model:
  name: "intfloat/multilingual-e5-small"

chunking:
  chunk_size: 1024
  chunk_overlap: 20

input_dir: "./data"
output_dir: "./graphrag_output"

# Ignore patterns for file processing
ignore_patterns:
  - "*.tmp"
  - "*.log"
  - "*.cache"
  - "*.bak"
  - "*.swp"
  - "*.DS_Store"
  - "Thumbs.db"
  - ".git/*"
  - ".gitignore"
  - "__pycache__/*"
  - "*.pyc"
  - "node_modules/*"
  - ".env"
  - ".env.*"

vector_store:
  type: "lancedb" # or "default"
  lancedb:
    uri: "lancedb_main"
    table_name: "vectors"

community_vector_store:
  type: "lancedb" # or "default"
  lancedb:
    uri: "lancedb_communities"
    table_name: "community_vectors"

entity_vector_store:
  type: "lancedb" # or "default"
  lancedb:
    uri: "lancedb_entities"
    table_name: "entities_vectors"

community_detection:
  max_cluster_size: 10
  use_lcc: True
  seed: 42